# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSshtunnel < Formula
  desc "A tiny ssh tunnel implemented in GO. It's main purpose is to establish an SSH connection from a Docker container to a jumpbox and redirect all outgoing TCP traffic over this connection."
  homepage "https://github.com/dueckminor/go-sshtunnel/"
  version "1.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dueckminor/go-sshtunnel/releases/download/v1.8/sshtunnel-1.8-darwin-arm64.tar.gz"
      sha256 "d192ba44874ac425e8b6c2995f911c497d01bc34c4daedc749cc4f830acbe98d"

      def install
        bin.install "sshtunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dueckminor/go-sshtunnel/releases/download/v1.8/sshtunnel-1.8-darwin-amd64.tar.gz"
      sha256 "8c8e3fb38db91f1f834cc0511b868d578b8b428f8d000e15571a6a1806b71b36"

      def install
        bin.install "sshtunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dueckminor/go-sshtunnel/releases/download/v1.8/sshtunnel-1.8-linux-arm64.tar.gz"
      sha256 "5990fb0f34cf1b469f75fd309a31bf5c18860099cdb7ad2d6a83c710530c2620"

      def install
        bin.install "sshtunnel"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dueckminor/go-sshtunnel/releases/download/v1.8/sshtunnel-1.8-linux-amd64.tar.gz"
      sha256 "bae433c752f1cc05cb325c713c48c3b0ff71ea5746d67f1bc5b1be2561602668"

      def install
        bin.install "sshtunnel"
      end
    end
  end

  test do
    system "#{bin}/sshtunnel --version"
  end
end
