#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

VERSION=
FILE_VERSION=""
ADDITIONAL_ARGS=()
if [[ -n "${1}" ]]; then
    VERSION="${1//refs\/tags\//}"
    ADDITIONAL_ARGS=("-ldflags=-X github.com/dueckminor/go-sshtunnel/commands.version=${VERSION}")
    FILE_VERSION="${VERSION}-"
fi

echo "compiling sshtunnel..."
mkdir -p "${DIR_ROOT}/gen/linux_amd64"
GOOS=linux GOARCH=amd64 go build "${ADDITIONAL_ARGS[@]}" -o "${DIR_ROOT}/gen/linux_amd64/sshtunnel" main.go

mkdir -p "${DIR_ROOT}/gen/linux_arm64"
GOOS=linux GOARCH=arm64 go build "${ADDITIONAL_ARGS[@]}" -o "${DIR_ROOT}/gen/linux_arm64/sshtunnel" main.go

go build "${ADDITIONAL_ARGS[@]}" -o "${DIR_ROOT}/gen/sshtunnel" main.go

ADDITIONAL_TAR_ARGS=()
if [[ "$(uname -s)" == "Linux" ]]; then
    ADDITIONAL_TAR_ARGS+=("--owner" "0")
    ADDITIONAL_TAR_ARGS+=("--group" "0")
fi

mkdir -p "${DIR_ROOT}/gen/assets"
pushd "${DIR_ROOT}/gen/linux_amd64"
    tar czf "${DIR_ROOT}/gen/assets/sshtunnel-${FILE_VERSION}linux-amd64.tar.gz" "${ADDITIONAL_TAR_ARGS[@]}" sshtunnel
popd

pushd "${DIR_ROOT}/gen/linux_arm64"
    tar czf "${DIR_ROOT}/gen/assets/sshtunnel-${FILE_VERSION}linux-arm64.tar.gz" "${ADDITIONAL_TAR_ARGS[@]}" sshtunnel
popd
