#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

echo "compiling sshtunnel..."
mkdir -p "${DIR_ROOT}/build"
GOOS=linux GOARCH=amd64 go build -o "${DIR_ROOT}/build/sshtunnel" main.go
