#!/usr/bin/env bash

set -e

DIR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"

if [[ ! -f "${DIR_ROOT}/gen/wget" ]]; then
    cp "$(command -v wget)" "${DIR_ROOT}/gen/wget"
fi

GetHttpPort() {
    "${DIR_ROOT}/gen/sshtunnel" list-proxies | yaml2json | jq -r '.proxies[] | select(.type=="http") | .port'
}

HTTP_PORT="$(GetHttpPort)"

echo "Using HTTP-Proxy at port ${HTTP_PORT}"

export ALL_PROXY="http://localhost:${HTTP_PORT}"
export DYLD_INSERT_LIBRARIES="${DIR_ROOT}/gen/libsshtunnel_client_hook.dylib"
export DYLD_FORCE_FLAT_NAMESPACE=1

"${DIR_ROOT}/gen/wget" https://github.tools.sap -o /dev/null
