name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Go 1.24
        uses: actions/setup-go@v7
        with:
          go-version: 1.26
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v7

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIS_SERVICE_USER_TOKEN: ${{ secrets.TIS_SERVICE_USER_TOKEN }}
